@baseUrl = http://localhost:5007
@deliveryId = e92c39cc-c656-44f7-8b8f-20af908a8744

### Create delivery
POST {{baseUrl}}/api/deliveries
Content-Type: application/json

{
  "code": "DEL-001",
  "originLatitude": 52.520008,
  "originLongitude": 13.404954,
  "destinationLatitude": 52.5170365,
  "destinationLongitude": 13.3888599
}

### Get all deliveries
GET {{baseUrl}}/api/deliveries

### Get delivery by id
GET {{baseUrl}}/api/deliveries/{{deliveryId}}

### Transition to Assigned
POST {{baseUrl}}/api/deliveries/{{deliveryId}}/transition
Content-Type: application/json

{
  "targetState": "Assigned"
}

### Get route
GET {{baseUrl}}/api/deliveries/{{deliveryId}}/route

### Transition to InTransit
POST {{baseUrl}}/api/deliveries/{{deliveryId}}/transition
Content-Type: application/json

{
  "targetState": "InTransit"
}

### Get events
GET {{baseUrl}}/api/deliveries/{{deliveryId}}/events