@baseUrl = http://localhost:5007

### Create vehicle
POST {{baseUrl}}/api/vehicles
Content-Type: application/json

{
  "name": "VEH-001"
}
> {%
    client.global.set("vehicleId", response.body.id)
%}

### Create delivery
POST {{baseUrl}}/api/deliveries
Content-Type: application/json

{
  "code": "DEL-001",
  "originLatitude": 52.520008,
  "originLongitude": 13.404954,
  "destinationLatitude": 52.5170365,
  "destinationLongitude": 13.3888599
}
> {%
    client.global.set("deliveryId", response.body.id)
%}

### Plan delivery
POST {{baseUrl}}/api/deliveries/{{deliveryId}}/plan

### Assign vehicle
POST {{baseUrl}}/api/deliveries/{{deliveryId}}/assign-vehicle
Content-Type: application/json

{
  "vehicleId": "{{vehicleId}}"
}

### Start delivery
POST {{baseUrl}}/api/deliveries/{{deliveryId}}/start

### Get delivery
GET {{baseUrl}}/api/deliveries/{{deliveryId}}

### Get route
GET {{baseUrl}}/api/deliveries/{{deliveryId}}/route

### Get events
GET {{baseUrl}}/api/deliveries/{{deliveryId}}/events

### Close delivery
POST {{baseUrl}}/api/deliveries/{{deliveryId}}/close

### Clear global
GET https://httpbin.org/status/204

> {%
    client.global.clearAll()
%}